<?php
namespace api\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use EasyWeChat\Factory;



/**
 * Site controller
 */
class SiteController extends CommonController
{
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        $action= parent::actions(); // TODO: Change the autogenerated stub
        unset($action['index']);
        unset($action['create']);
        unset($action['update']);
        unset($action['delete']);
    }

    public function actionIndex()
    {

        $config = [
            'app_id' => 'wxbb66cd84d793b2de',
            'secret' => 'a380e4af86ca899cd0b969c64fbb4afe',
            'token' => 'a380e4af86ca899cd0b969c64fbb4afe',
            'response_type' => 'array',
            //...
        ];

        $app = Factory::officialAccount($config);

        $response = $app->server->serve();

        // 将响应输出
        $response->send();exit; // Laravel 里请使用：return $response;
    }

}
